version: '3.8'


services:
  auth-app:
    image: dleclercpro/dummy-authenticator:latest
    container_name: auth-app
    networks:
      - custom
    depends_on:
      - auth-redis
    environment:
      NODE_ENV: production

  auth-nginx:
    container_name: auth-nginx
    image: dleclercpro/ssl-reverse-proxy:latest
    restart: always
    ports:
      - 443:443 # HTTPS
      - 80:80   # HTTP
    networks:
      - custom
    volumes:
      - letsencrypt:/etc/letsencrypt # Keep SSL certificates
    depends_on:
      - auth-app
    env_file:
      - .env

  auth-redis:
    image: redis:latest
    container_name: auth-redis
    restart: always
    networks:
      - custom
    volumes:
      - redis:/data


volumes:
  redis:
  letsencrypt:


networks:
  # Custom network to communicate with external services/containers
  custom:
    external: true