version: '3.8'


services:
  auth-app:
    image: dleclercpro/dummy-authenticator:v2.2.0
    container_name: auth-app
    ports:
      - 80:8000
    depends_on:
      - auth-redis
    environment:
      NODE_ENV: production

  auth-redis:
    image: redis:latest
    container_name: auth-redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data


volumes:
  redis: