version: '3.8'


services:
  app:
    image: dleclercpro/dummy-authenticator:v2.2.0
    container_name: dummy-authenticator--app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8000
    networks:
      - app
    depends_on:
      - db
    environment:
      NODE_ENV: production

  db:
    image: redis:latest
    container_name: dummy-authenticator--db
    ports:
      - 6379:6379
    networks:
      - app
    volumes:
      - db:/data


networks:
  app:
    driver: bridge


volumes:
  db: