version: '3.8'

services:
  app:
    container_name: dummy-authenticator
    image: dleclercpro/dummy-authenticator:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8000
    environment:
      NODE_ENV: production